# PostgreSQL Database Configuration (reactive with R2DBC for WebFlux compatibility)
spring.r2dbc.url=r2dbc:postgresql://dpg-d5eei9be5dus73fmb5ig-a.oregon-postgres.render.com:5432/stockdoc?sslMode=require
spring.r2dbc.username=stockdoc_user
spring.r2dbc.password=P7HjFfHUw37PCgGPJ7p5H5R6LgJd4tkZ


# MinIO Configuration
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=stockdoc

# Parse Configuuration
parsing.api.url=https://lcgfy76ct94esfka.aistudio-app.com/layout-parsing
parsing.api.token=e5906e8a733a30090fb09369175fead3d9e4bca3

# Activer les logs
logging.level.org.springframework.web=DEBUG
logging.level.Projects.Network=DEBUG