# PostgreSQL Database Configuration (reactive with R2DBC for WebFlux compatibility)
spring.r2dbc.url=r2dbc:postgresql://dpg-d5eei9be5dus73fmb5ig-a.oregon-postgres.render.com:5432/stockdoc?sslMode=require
spring.r2dbc.username=stockdoc_user
spring.r2dbc.password=P7HjFfHUw37PCgGPJ7p5H5R6LgJd4tkZ


# Supabase Configuration
supabase.url=https://netqqstmicwcxeooodyi.supabase.co
supabase.service-role-key=sb_secret_a7o6aY0yPktNQTBphGuaRw_vFFavuwg
supabase.bucket=Documents

# Parse Configuuration
parsing.api.url=https://lcgfy76ct94esfka.aistudio-app.com/layout-parsing
parsing.api.token=e5906e8a733a30090fb09369175fead3d9e4bca3

# Activer les logs
logging.level.org.springframework.web=DEBUG
logging.level.Projects.Network=DEBUG

server.port=${PORT:8080}
google.client-id=301304954440-uke10vjabllkae3hlpiqjs0ukvmibqbg.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=http://new-backend-network.onrender.com/api/auth/google/callback

reactor.netty.pool.maxConnections=100
reactor.netty.pool.maxIdleTime=20s

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

server.url=${RENDER_EXTERNAL_URL:http://localhost:8080}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always