package Projects.Network.repository;

import Projects.Network.model.DocumentEntity;
import org.springframework.data.r2dbc.repository.R2dbcRepository;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.UUID;

/**
 * DocumentRepository
 *
 * Repository interface responsible for data access operations
 * related to {@link DocumentEntity}.
 *
 * This interface extends R2dbcRepository to provide reactive
 * CRUD operations for the "documents" table.
 *
 * Spring Data R2DBC automatically generates the implementation
 * of this repository at runtime based on method signatures.
 *
 * This repository belongs to the Repository layer and must not
 * contain any business logic.
 *
 * Author: Thomas Djotio Ndié
 * Creation date: 2026-01-02
 */
public interface DocumentRepository extends R2dbcRepository<DocumentEntity, UUID> {

    /**
     * Retrieves a document using its MinIO storage path.
     *
     * This method allows searching for a document based on the
     * object storage reference used in MinIO.
     *
     * Spring Data R2DBC derives the query automatically from
     * the method name.
     *
     * @param minioPath the full path or object key of the document in MinIO
     * @return a Mono emitting the corresponding DocumentEntity if found
     */
    Mono<DocumentEntity> findByMinioPath(String minioPath);

    /**
     * Retrieves all documents owned by a specific user.
     *
     * This method returns every document associated with the given
     * user identifier.
     *
     * The implementation is automatically generated by Spring Data
     * R2DBC based on the method naming convention.
     *
     * @param userId the unique identifier of the user
     * @return a Flux emitting all DocumentEntity objects belonging to the user
     */
    Flux<DocumentEntity> findAllByUserId(UUID userId);
}
